apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/aksoydoruk/argocd-nexus.git'
    targetRevision: main
    path: 10-nexus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
