apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nexus-ui
  namespace: nexus
spec:
  host: $(NEXUS_UI_HOST)
  to:
    kind: Service
    name: nexusrepo-sonatype-nexus-service
  port:
    targetPort: application
  tls:
    termination: edge
