apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexusrepo
  namespace: nexus
spec:
  replicas: 1

  # --- Storage (IMPORTANT for CPD mirroring) ---
  persistence:
    enabled: true
    storageClass: ocs-storagecluster-ceph-rbd
    accessMode: ReadWriteOnce
    storageSize: 500Gi

  # --- Resource tuning (avoid OOM / throttling) ---
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "10Gi"

  # Optional: JVM tuning (recommended for stability)
  env:
  - name: INSTALL4J_ADD_VM_PARAMS
    value: "-Xms2g -Xmx4g -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data/javaprefs"

