apiVersion: v1
kind: Service
metadata:
  name: nexus-docker
  namespace: nexus
spec:
  selector:
    app: sonatype-nexus
    app.kubernetes.io/instance: nexus
    app.kubernetes.io/name: nexusrepo-sonatype-nexus
  ports:
    - name: docker
      port: 5000
      targetPort: 5000
  type: ClusterIP
